extends Node

signal game_started()
signal turn_started(player_id: int, turn_number: int)
signal turn_ended(player_id: int)
signal epoch_ended(epoch: int)
signal game_over(winner_id: int)
signal action_move_requested(from_city: String, to_city: String)
signal action_build_temple_requested(city: String)
signal action_play_card_requested(card_id: String, target_peer_id: int)
signal action_end_turn_requested()
signal player_state_updated(peer_id: int, state_dict: Dictionary)
signal card_drawn(peer_id: int, card_id: String)
signal card_played(peer_id: int, card_id: String, target_peer_id: int)
signal accident_drawn(peer_id: int, accident_id: String)
signal dice_rolled(peer_id: int, die1: int, die2: int)
signal city_clicked(city_name: String)
signal card_clicked(card_id: String)
signal declare_numbers_submitted(peer_id: int, numbers: Array[int])
